import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header } from "@/components/header";
import { Dock } from "@/components/dock";
import { ThemeProvider } from "@/components/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground selection:bg-primary/30 selection:text-primary-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Refined background for a more premium dark vibe */}
          <div className="fixed inset-0 -z-10 h-full w-full bg-background">
            <div className="absolute inset-0 bg-[radial-gradient(#489FB515_1px,transparent_1px)] [background-size:24px_24px] opacity-40" />
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(72,159,181,0.15),transparent)]" />
          </div>

          <Header />
          <main className="relative z-0">
            {children}
          </main>
          <Dock />

          <footer className="py-24 border-t bg-muted/30">
            <div className="container mx-auto px-4 text-center text-sm text-muted-foreground flex flex-col gap-4">
              <div className="text-xl font-bold tracking-tighter text-gradient mb-2">Bansari Makwana</div>
              <p>© {new Date().getFullYear()} Built with Next.js, TypeScript & Framer Motion.</p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
